// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/indigo_influx.proto

package indigoinflux

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InfluxTag struct {
	Name                 *wrappers.StringValue `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Folder               *wrappers.StringValue `protobuf:"bytes,2,opt,name=folder,proto3" json:"folder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *InfluxTag) Reset()         { *m = InfluxTag{} }
func (m *InfluxTag) String() string { return proto.CompactTextString(m) }
func (*InfluxTag) ProtoMessage()    {}
func (*InfluxTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8993388aedb6556, []int{0}
}

func (m *InfluxTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfluxTag.Unmarshal(m, b)
}
func (m *InfluxTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfluxTag.Marshal(b, m, deterministic)
}
func (m *InfluxTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfluxTag.Merge(m, src)
}
func (m *InfluxTag) XXX_Size() int {
	return xxx_messageInfo_InfluxTag.Size(m)
}
func (m *InfluxTag) XXX_DiscardUnknown() {
	xxx_messageInfo_InfluxTag.DiscardUnknown(m)
}

var xxx_messageInfo_InfluxTag proto.InternalMessageInfo

func (m *InfluxTag) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *InfluxTag) GetFolder() *wrappers.StringValue {
	if m != nil {
		return m.Folder
	}
	return nil
}

type InfluxEvent struct {
	Measurement          *wrappers.StringValue `protobuf:"bytes,1,opt,name=measurement,proto3" json:"measurement,omitempty"`
	Time                 *timestamp.Timestamp  `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Tags                 *InfluxTag            `protobuf:"bytes,3,opt,name=tags,proto3" json:"tags,omitempty"`
	Fields               *InfluxFields         `protobuf:"bytes,4,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *InfluxEvent) Reset()         { *m = InfluxEvent{} }
func (m *InfluxEvent) String() string { return proto.CompactTextString(m) }
func (*InfluxEvent) ProtoMessage()    {}
func (*InfluxEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8993388aedb6556, []int{1}
}

func (m *InfluxEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfluxEvent.Unmarshal(m, b)
}
func (m *InfluxEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfluxEvent.Marshal(b, m, deterministic)
}
func (m *InfluxEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfluxEvent.Merge(m, src)
}
func (m *InfluxEvent) XXX_Size() int {
	return xxx_messageInfo_InfluxEvent.Size(m)
}
func (m *InfluxEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_InfluxEvent.DiscardUnknown(m)
}

var xxx_messageInfo_InfluxEvent proto.InternalMessageInfo

func (m *InfluxEvent) GetMeasurement() *wrappers.StringValue {
	if m != nil {
		return m.Measurement
	}
	return nil
}

func (m *InfluxEvent) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *InfluxEvent) GetTags() *InfluxTag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *InfluxEvent) GetFields() *InfluxFields {
	if m != nil {
		return m.Fields
	}
	return nil
}

type InfluxFields struct {
	On                   *wrappers.BoolValue  `protobuf:"bytes,1,opt,name=on,proto3" json:"on,omitempty"`
	Brightness           *wrappers.FloatValue `protobuf:"bytes,11,opt,name=brightness,proto3" json:"brightness,omitempty"`
	CoolSetpoint         *wrappers.FloatValue `protobuf:"bytes,20,opt,name=coolSetpoint,proto3" json:"coolSetpoint,omitempty"`
	HeatSetpoint         *wrappers.FloatValue `protobuf:"bytes,21,opt,name=heatSetpoint,proto3" json:"heatSetpoint,omitempty"`
	Temperature          *wrappers.FloatValue `protobuf:"bytes,22,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity             *wrappers.FloatValue `protobuf:"bytes,23,opt,name=humidity,proto3" json:"humidity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InfluxFields) Reset()         { *m = InfluxFields{} }
func (m *InfluxFields) String() string { return proto.CompactTextString(m) }
func (*InfluxFields) ProtoMessage()    {}
func (*InfluxFields) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8993388aedb6556, []int{2}
}

func (m *InfluxFields) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfluxFields.Unmarshal(m, b)
}
func (m *InfluxFields) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfluxFields.Marshal(b, m, deterministic)
}
func (m *InfluxFields) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfluxFields.Merge(m, src)
}
func (m *InfluxFields) XXX_Size() int {
	return xxx_messageInfo_InfluxFields.Size(m)
}
func (m *InfluxFields) XXX_DiscardUnknown() {
	xxx_messageInfo_InfluxFields.DiscardUnknown(m)
}

var xxx_messageInfo_InfluxFields proto.InternalMessageInfo

func (m *InfluxFields) GetOn() *wrappers.BoolValue {
	if m != nil {
		return m.On
	}
	return nil
}

func (m *InfluxFields) GetBrightness() *wrappers.FloatValue {
	if m != nil {
		return m.Brightness
	}
	return nil
}

func (m *InfluxFields) GetCoolSetpoint() *wrappers.FloatValue {
	if m != nil {
		return m.CoolSetpoint
	}
	return nil
}

func (m *InfluxFields) GetHeatSetpoint() *wrappers.FloatValue {
	if m != nil {
		return m.HeatSetpoint
	}
	return nil
}

func (m *InfluxFields) GetTemperature() *wrappers.FloatValue {
	if m != nil {
		return m.Temperature
	}
	return nil
}

func (m *InfluxFields) GetHumidity() *wrappers.FloatValue {
	if m != nil {
		return m.Humidity
	}
	return nil
}

func init() {
	proto.RegisterType((*InfluxTag)(nil), "indigo_influx.InfluxTag")
	proto.RegisterType((*InfluxEvent)(nil), "indigo_influx.InfluxEvent")
	proto.RegisterType((*InfluxFields)(nil), "indigo_influx.InfluxFields")
}

func init() {
	proto.RegisterFile("proto/indigo_influx.proto", fileDescriptor_a8993388aedb6556)
}

var fileDescriptor_a8993388aedb6556 = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xdd, 0x8a, 0xd4, 0x30,
	0x14, 0xc7, 0x99, 0x5a, 0x06, 0x3d, 0x5d, 0x41, 0x82, 0x1f, 0x71, 0x14, 0x57, 0xe6, 0x4a, 0x44,
	0x5a, 0x71, 0x05, 0x2f, 0x44, 0x85, 0x01, 0x57, 0xf6, 0xb6, 0x3b, 0x78, 0xe1, 0x8d, 0x64, 0xda,
	0xd3, 0x4c, 0x20, 0x5f, 0x24, 0xa9, 0x1f, 0x6f, 0xeb, 0x2b, 0xf8, 0x06, 0xb2, 0x49, 0x77, 0xe8,
	0xec, 0x08, 0x9d, 0xcb, 0xe6, 0xfc, 0x7e, 0xe7, 0x9f, 0x73, 0x42, 0xe1, 0xb1, 0x75, 0x26, 0x98,
	0x4a, 0xe8, 0x56, 0x70, 0xf3, 0x5d, 0xe8, 0x4e, 0xf6, 0xbf, 0xca, 0x78, 0x46, 0xee, 0xee, 0x1d,
	0x2e, 0x4e, 0xb9, 0x31, 0x5c, 0x62, 0x15, 0x8b, 0x9b, 0xbe, 0xab, 0x82, 0x50, 0xe8, 0x03, 0x53,
	0x36, 0xf1, 0x8b, 0x67, 0x37, 0x81, 0x9f, 0x8e, 0x59, 0x8b, 0xce, 0xa7, 0xfa, 0xd2, 0xc3, 0x9d,
	0x8b, 0xd8, 0x6a, 0xcd, 0x38, 0x79, 0x0d, 0xb9, 0x66, 0x0a, 0xe9, 0xec, 0xf9, 0xec, 0x45, 0xf1,
	0xe6, 0x69, 0x99, 0xdc, 0xf2, 0xda, 0x2d, 0x2f, 0x83, 0x13, 0x9a, 0x7f, 0x65, 0xb2, 0xc7, 0x3a,
	0x92, 0xe4, 0x2d, 0xcc, 0x3b, 0x23, 0x5b, 0x74, 0x34, 0x3b, 0xc2, 0x19, 0xd8, 0xe5, 0x9f, 0x19,
	0x14, 0x29, 0xf5, 0xf3, 0x0f, 0xd4, 0x81, 0x7c, 0x84, 0x42, 0x21, 0xf3, 0xbd, 0x43, 0x85, 0x3a,
	0x1c, 0x15, 0x3f, 0x16, 0x48, 0x09, 0xf9, 0xd5, 0xdc, 0xc3, 0x1d, 0x16, 0x07, 0xe2, 0xfa, 0x7a,
	0x29, 0x75, 0xe4, 0xc8, 0x2b, 0xc8, 0x03, 0xe3, 0x9e, 0xde, 0x8a, 0x3c, 0x2d, 0xf7, 0x17, 0xbd,
	0xdb, 0x47, 0x1d, 0x29, 0x72, 0x06, 0xf3, 0x4e, 0xa0, 0x6c, 0x3d, 0xcd, 0x23, 0xff, 0xe4, 0xbf,
	0xfc, 0x79, 0x44, 0xea, 0x01, 0x5d, 0xfe, 0xcd, 0xe0, 0x64, 0x5c, 0x20, 0x2f, 0x21, 0x33, 0x7a,
	0x18, 0xed, 0xf0, 0x86, 0x2b, 0x63, 0x64, 0x1a, 0x2c, 0x33, 0x9a, 0xbc, 0x07, 0xd8, 0x38, 0xc1,
	0xb7, 0x41, 0xa3, 0xf7, 0xb4, 0x18, 0x52, 0x6f, 0x3a, 0xe7, 0xd2, 0xb0, 0x90, 0xa4, 0x11, 0x4e,
	0x3e, 0xc1, 0x49, 0x63, 0x8c, 0xbc, 0xc4, 0x60, 0x8d, 0xd0, 0x81, 0xde, 0x9f, 0xd6, 0xf7, 0x84,
	0xab, 0x06, 0x5b, 0x64, 0x61, 0xd7, 0xe0, 0xc1, 0x11, 0x0d, 0xc6, 0x02, 0xf9, 0x00, 0x45, 0x40,
	0x65, 0xd1, 0xb1, 0xd0, 0x3b, 0xa4, 0x0f, 0xa7, 0xfd, 0x31, 0x4f, 0xde, 0xc1, 0xed, 0x6d, 0xaf,
	0x44, 0x2b, 0xc2, 0x6f, 0xfa, 0x68, 0xda, 0xdd, 0xc1, 0xab, 0x35, 0x9c, 0x7a, 0xd5, 0xbb, 0x4e,
	0xa2, 0xf7, 0x65, 0x63, 0x54, 0xc5, 0x9d, 0x6d, 0x86, 0xbf, 0x28, 0xbd, 0xd5, 0xea, 0xde, 0x45,
	0xfc, 0x4a, 0x2f, 0xf3, 0xc5, 0xd9, 0xe6, 0xdb, 0x94, 0xb2, 0x99, 0xc7, 0xd0, 0xb3, 0x7f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x47, 0x3b, 0x7f, 0x10, 0x95, 0x03, 0x00, 0x00,
}
