# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from indigo_protobuf import indigo_pb2 as indigo__protobuf_dot_indigo__pb2


class TranslatorStub(object):
    """A service that translates raw JSON messages to the above structures
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_stream(
                '/indigo.Translator/Subscribe',
                request_serializer=indigo__protobuf_dot_indigo__pb2.SubscribeArgs.SerializeToString,
                response_deserializer=indigo__protobuf_dot_indigo__pb2.IndigoUnknownMessage.FromString,
                )


class TranslatorServicer(object):
    """A service that translates raw JSON messages to the above structures
    """

    def Subscribe(self, request, context):
        """Subscribe to ongoing message updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranslatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=indigo__protobuf_dot_indigo__pb2.SubscribeArgs.FromString,
                    response_serializer=indigo__protobuf_dot_indigo__pb2.IndigoUnknownMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'indigo.Translator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Translator(object):
    """A service that translates raw JSON messages to the above structures
    """

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/indigo.Translator/Subscribe',
            indigo__protobuf_dot_indigo__pb2.SubscribeArgs.SerializeToString,
            indigo__protobuf_dot_indigo__pb2.IndigoUnknownMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
